stages:
  - plan
  - apply

variables:
  TF_VERSION: "1.0.0"
  TF_WORKSPACE: ${CI_COMMIT_REF_NAME}

cache:
  paths:
    - .terraform/

before_script:
  - terraform --version
  - terraform init

plan:
  stage: plan
  script:
    - terraform plan -var-file="environments/${CI_COMMIT_REF_NAME}/terraform.tfvars" -out=tfplan
  only:
    - dev
    - staging
    - production

apply:
  stage: apply
  script:
    - terraform apply -var-file="environments/${CI_COMMIT_REF_NAME}/terraform.tfvars" -auto-approve
  only:
    - dev
    - staging
    - production
  when: manual

