stages:
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  AWS_REGION: "us-west-2"

before_script:
  - terraform init

# Plan job for Development
plan_dev:
  stage: plan
  script:
    - terraform workspace select dev || terraform workspace new dev
    - terraform plan -out=dev.tfplan
  only:
    - dev

# Apply job for Development
apply_dev:
  stage: apply
  script:
    - terraform workspace select dev
    - terraform apply -auto-approve dev.tfplan
  only:
    - dev
  when: manual  # Manual deployment for safety

# Plan job for Staging
plan_staging:
  stage: plan
  script:
    - terraform workspace select staging || terraform workspace new staging
    - terraform plan -out=staging.tfplan
  only:
    - staging

# Apply job for Staging
apply_staging:
  stage: apply
  script:
    - terraform workspace select staging
    - terraform apply -auto-approve staging.tfplan
  only:
    - staging
  when: manual  # Manual deployment for safety

# Plan job for Production
plan_prod:
  stage: plan
  script:
    - terraform workspace select production || terraform workspace new production
    - terraform plan -out=prod.tfplan
  only:
    - main

# Apply job for Production
apply_prod:
  stage: apply
  script:
    - terraform workspace select production
    - terraform apply -auto-approve prod.tfplan
  only:
    - main
  when: manual  # Manual deployment for safety
  allow_failure: false  # Prevent merging if the production job fails
